# Project information
site_name: "Business Analytics: Data Analysis & Decision Making"
site_url: "https://thloggicalone.github.io/BA_for_Solico/" # Replace with your GitHub Pages URL
site_author: "Ali Hosseipuran"
site_description: "Course materials for the Business Analytics training program at Solico Group."

# Repository
repo_url: "https://github.com/TheLoggicalOne/BA_for_Solico" # Replace with your GitHub repo URL
repo_name: "View on GitHub"
edit_uri: "" # Hides the 'Edit on GitHub' link

# Copyright
copyright: "Copyright &copy; 2025 Ali Hosseipuran. All rights reserved."

# Theme Configuration
theme:
  name: material
  language: en
  logo: assets/logo.png # Optional: create an 'assets' folder in 'docs' for images
  favicon: assets/logo.png
  palette:
    # Palette toggle for light/dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true

# Navigation Structure
nav:
  - 'Home': 'index.md'
  - 'Modern Analyst Mindset': 'mindset.md'
  - 'Syllabus & Schedule': 'syllabus.md'
  - 'Weekly Sessions':
    - 'Week 1: Kickoff & The Big Picture': 'weeks/week01.md'
    - 'Week 2: From Decision Making to Optimization': 'weeks/week02.md'
    # ... add all 14 weeks here
  - 'Resources & Tools': 'resources.md'
  - 'Projects & Competition': 'projects.md'
