# Project information
site_name: "Business Analytics: Data Analysis & Decision Making"
site_url: "https://thloggicalone.github.io/BA_for_Solico/" # Replace with your GitHub Pages URL
site_author: "Ali Hosseipuran"
site_description: "Course materials for the Business Analytics training program at Solico Group."

# Repository
repo_url: "https://github.com/TheLoggicalOne/BA_for_Solico" # Replace with your GitHub repo URL
repo_name: "View on GitHub"
edit_uri: "" # Hides the 'Edit on GitHub' link

# Copyright
copyright: "Copyright &copy; 2025 Ali Hosseipuran. All rights reserved."

# Theme Configuration
theme:
  name: material
  language: en
  logo: assets/logo.png # Optional: create an 'assets' folder in 'docs' for images
  favicon: assets/logo.png
  palette:
    # Palette toggle for light/dark mode
    - scheme: slate
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    
    - scheme: default
      primary: indigo
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
     permalink: true 
  - pymdownx.arithmatex:
     inline_syntax : ['dollar', 'round']
     generic: true      

# Navigation Structure
nav:
  - 'Home': 'index.md'
  - 'Modern Analyst Mindset': 'mindset.md'
  - 'Syllabus & Schedule': 'syllabus.md'
  - 'Weekly Sessions':
    - 'Overview': 'weeks/index.md' # This is your "Weekly Sessions" overview page
    - 'Week 1: Kickoff & The Big Picture': 'weeks/week01.md' # Explicitly list each week
    - 'Week 2: From Decision Making to Optimization': 'weeks/week02.md'
    - 'Week 3: From Optimization to Simulation': 'weeks/week03.md'
    - 'Week 4: From Simulation to Optimization': 'weeks/week04.md'
    - 'Week 5: From Optimization to Simulation': 'weeks/week05.md'
    - 'Week 6: From Simulation to Optimization': 'weeks/week06.md'
    - 'Week 14: Final Projects & Future of Solico': 'weeks/week14.md'
  - 'Concepts & Principles': 
    - 'Overview': 'concepts/index.md'
    # ... add all 14 weeks here
  - 'Resources & Tools': 'resources.md'
  - 'Projects & Competition': 'projects.md'


extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
  - js/math.js  # your custom initialization file
